name: build-linux-container
on:
  workflow_dispatch:

jobs:
  linux-ubuntu:
    runs-on: ubuntu-latest
    env:
      tag: 2.3.1-ubuntu20
    steps:
      - uses: actions/checkout@v3
      - name: Build runtime container
        run: |
          cd ${{ github.workspace }}/build/docker/dotnet6-paddle
          docker build . -t sdflysha/dotnet6-paddle:$tag
      - name: Build sdk container
        run: |
          cd ${{ github.workspace }}/build/docker/dotnet6sdk-paddle
          docker build . -t sdflysha/dotnet6sdk-paddle:$tag
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Push runtime to dockerhub
        run: docker push sdflysha/dotnet6-paddle:$tag
      - name: Push sdk to dockerhub
        run: docker push sdflysha/dotnet6sdk-paddle:$tag